os:
  - linux
  
services:
  - docker
  
language: java

jdk:
  - oraclejdk8

install: true

sudo: required

cache:
  directories:
    - $HOME/.m2
    
script:
  - mvn clean install
  - mvn clean package docker:build

branches:
  only:
  - master
  - develop

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=goleador
  - export VERSION=`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
  - test "$TRAVIS_BRANCH" == 'master' && (docker tag $REPO murillocg/$REPO; docker tag $REPO murillocg/$REPO:$VERSION; docker push murillocg/$REPO:latest; docker push murillocg/$REPO:$VERSION)
  - test "$TRAVIS_BRANCH" == 'develop' && (docker tag $REPO murillocg/$REPO:snapshot; docker push murillocg/$REPO:snapshot)
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
