version: '2'
services:
    goleador-postgresql:
        container_name: goleador-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/goleador/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=goleador
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
